# Welcome to Jekyll!
#
# This config file is used for settings that apply to your entire site.
# If you need to help with any of the settings, check out the Jekyll
# documentation at https://jekyllrb.com/docs/configuration/
#
# The settings with values are default settings used by Jekyll. If you
# change any of these, Jekyll will use the new settings instead.
#
# SITE SETTINGS
title: Binary Spells
author: Leandro Peralta
email: argenkiwi@hotmai.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog about coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://argenkiwi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: argenkiwi
github_username: argenkiwi

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
