# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-50425306-5
favicon: /favicon.png
twitter: soflete
google_plus: 114521903221329576323
fb_admins:
fb_app_id:
